### PR TITLE
Upgrade runtime to 22.08

### PR DESCRIPTION
**Pull request by proletarius101**

### CODE REVIEW

**Comment by proletarius101** [comment]
bot, build [org.freedesktop.Sdk.Extension.openjdk17](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk17)

**Comment by proletarius101** [comment]
bot, build org.freedesktop.Sdk.Extension.openjdk17

**Comment by hfiguiere** [comment]
this is not a transient failure.

**Comment by hfiguiere** [comment]
see https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/pull/28

**Comment by proletarius101** [comment]
> see [flathub/org.freedesktop.Sdk.Extension.openjdk11#28](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/pull/28)

Thanks that's helpful

**Comment by proletarius101** [comment]
bot, build org.freedesktop.Sdk.Extension.openjdk17

**Comment by nbenitez** [comment]
Gentle ping to merge this @mbooth101

**Comment by hfiguiere** [comment]
Created the branch. it should be available in a few hours.

**Comment by guihkx** [comment]
Thank you, @hfiguiere! If you have some time, please take a look at https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/pull/28 as well. Thanks again.

**Comment by nbenitez** [comment]
> Created the branch. it should be available in a few hours.

@hfiguiere  @barthalion It's no available on flathub yet (see below).. some error in the publishing step?

```
flatpak install --system org.freedesktop.Sdk.Extension.openjdk17
Looking for matches…
Similar refs found for ‘org.freedesktop.Sdk.Extension.openjdk17’ in remote ‘flathub’ (system):

   1) runtime/org.freedesktop.Sdk.Extension.openjdk17/x86_64/20.08
   2) runtime/org.freedesktop.Sdk.Extension.openjdk17/x86_64/21.08

Which do you want to use (0 to abort)? [0-2]:
```

**Comment by hfiguiere** [comment]
I guess the build failed.

**Comment by hfiguiere** [comment]
retriggered

**Comment by hfiguiere** [comment]
will be available in a few hours.

**Pull request closed without merging**
